version: '3.8'
services:
  java-gradle-app:
    image: kalki2878/java-gradle-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=my-pwd

